const colleges = [
	"(A.B.M.S.) Akhil Bharatiya Maratha Shikshan Parishad's College of Engineering & Research Address: S. No. 103, Shahu College Campus, Parvati, Taluka: Pune (corporation Area) District: Pune - 411009",
	"A G PATIL INSTITUTE OF TECHNOLOGY 18 2A2 PRATANAGER SOREGON ROAD",
	"A J Institute of Engineering and Technology Mangaluru",
	"A P Shah Institute Of Technology",
	"A R Engineering College",
	"A. D. Patel Institute of Technology",
	"A. M. Reddy Memorial College of Engineering and Technology",
	"A.K.T. Memorial College of Engineering & Technology",
	"A.V.C. College of Engineering",
	"AAA COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Aalim Muhammed Salegh College of Engineering",
	"ABACUS Institute of Engineering and Management",
	"ABES Engineering College",
	"ABES INSTITUTE OF TECHNOLOGY, GHAZIABAD",
	"Academy of Maritime Education and Training",
	"ACADEMY OF TECHNOLOGY",
	"ACE Engineering college",
	"Acharya Institute of Technology",
	"Acropolis Institute Of Technology And Research",
	"ACS COLLEGE OF ENGINEERING",
	"ADARSHA INSTITUTE OF TECHNOLOGY, LINGADJEERA GOLLAHALLI, DEVANAHALLI",
	"Adhi College of Engineering and Technology",
	"Adhiparasakthi College of Engineering",
	"Adhiparasakthi Engineering College",
	"Adhiyamaan College of Engineering(Autonomous)",
	"Adi Shankara Institute of Engineering and Technology",
	"Adichunchanagiri Institute of Technology",
	"Adikavi Nannaya University",
	"Adithya Institute of Technology",
	"ADITYA COLLEGE OF ENGINEERING",
	"Aditya College of Engineering",
	"Aditya College of Engineering & Technology",
	"Aditya Engineering College",
	"Aditya Institute of Technology and Management",
	"Agnel Institute of Technology and Design",
	"Agni College of Technology",
	"Agriculture University,Jodhpur",
	"Ahmednagar Jilha Maratha Vidya Prasarak Samajs Ahmednagar Shri.Chhatrapati Shivaji Maharaj College of Engineering, Nepti, Address: Nepti Nagar Kalyan Road, Ahmednagar, Taluka: Ahmednagar, District: Ahmednagar",
	"Ajay Binay Institute of Technology, (ABIT), Cuttack",
	"Ajay Kumar Garg Engineering College",
	"Ajeenkya D Y Patil University",
	"Ajeenkya DY Patil School of Engineering",
	"AKSHAYA COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Al-Azhar College of Engineering & Technology, Perumpillichira, Thodupuzha",
	"Alagappa Chettiar Government College of Engineering and Technology",
	"ALBERTIAN INSTITUTE OF SCIENCE AND TECHNOLOGY - AISAT",
	"Aldel Education Trust's St. John College of Engineering",
	"Aliah University, Kolkata",
	"Aligarh Muslim University",
	"All India Shivaji Memorial Societys College of Engineering, Pune",
	"All India Shri Shivaji Memorial Society`s Institute of Information Technology",
	"Alvas Institute of Engineering and Technology, MOODBIDRI",
	"AMAL JYOTHI COLLEGE OF ENGINEERING",
	"Aman Bhalla Institute of Engg. & Tech, Jhakolari, Pathankot",
	"Ambala College of Engineering & Applied Research",
	"Ambalika Institute of Management and Technology",
	"Amity University",
	"Amity University",
	"Amity University Haryana, Gurgaon",
	"Amity University Patna",
	"Amity University Rajasthan,Jaipur",
	"Amity University, Gwalior",
	"Amity University, Jharkhand",
	"Amity University, Mumbai",
	"Amity University, Raipur",
	"Amrita College of Engineering and Technology, Nagercoil",
	"Amrita Vishwa Vidyapeetham",
	"Amritsar Group of Colleges",
	"Amrutvahini College of Engineering, Sangamner",
	"ANAND INSTITUTE OF HIGHER TECHNOLOGY",
	"Anand International College of Engineering",
	"Andhra Loyola Institute of Engineering and Technology",
	"Angadi Instittute of Technology and Management",
	"Angel College of Engineering and Technology",
	"ANIL NEERUKONDA INSTITUTE OF TECHNOLOGY & SCIENCES",
	"Anjalai Ammal Mahalingam Engineering College",
	"ANJUMAN COLLEGE OF ENGINEERING & TECHNOLOGY",
	"Anna University",
	"Annai Vailankanni College of Engineering",
	"ANNAMACHARYA INSTITUTE OF TECHNOLOGY & SCIENCES",
	"Annamacharya Institute of Technology & Sciences",
	"ANNAMACHARYA INSTITUTE OF TECHNOLOGY AND SCIENCES",
	"Annamalai University",
	"Annapoorana Engineering College",
	"Annasaheb Dange College of Engineering and Technology, Ashta",
	"Anurag Engineering College",
	"Anurag University",
	"Arasu Engineering College",
	"Aravali College of Engineering & Management",
	"Aravali Institute of Technical Studies,Udaipur",
	"ARJUN COLLEGE OF TECHNOLOGY",
	"ARJUN COLLEGE OF TECHNOLOGY",
	"Army Institute of Technology",
	"Arulmurugan College of Engineering",
	"Arunachala College of Engineering for Women",
	"Arya College of Engg. & Information Technology, Jaipur",
	"Arya College of Engineering",
	"Aryabhatta College Of Engineering And Research Center",
	"Asan Memorial College of Engineering and Technology",
	"Asansol Engineering College",
	"Asia Pacific Institute of Information Technology",
	"ASIAN COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Assam Don Bosco University",
	"Assam Down Town University",
	"Assam Engineering College",
	"Atal Bihari Vajpayee Govt. Institute of Engineering Technology (Degree wing), Pragatinagar, Shimla",
	"IIIT Gwalior",
	"ATHARVA COLLEGE OF ENGINEERING",
	"ATME College of Engineering",
	"Atria Institute of Technology",
	"AU College of Engineering (A)",
	"Aurora`s Scientific & Technological Institute",
	"Avanthi Institute of Engineering & Technology, Tamaram Village, Makavarapalem mandal, Narsipatnam , Pin-531113. (CC-81)",
	"Avanthi Institute of Engineering and Technology",
	"Avanthi institute of Engineering and Technology",
	"AVS COLLEGE OF TECHNOLOGY ( FORMERLY AVS TECHNICAL CAMPUS)",
	"AVS Engineering College",
	"B K Birla Institute of Engineering & Technology, Pilani",
	"B. G. S. Institute of Technology",
	"B. P. Mandal College of Engineering, Madhepura",
	"B. P. Poddar Institute of Management & Technology",
	"B. S. Abdur Rahman Crescent Institute of Science and Technology",
	"B.L.D.E.A's V.P. Dr. P.G. Halakatti College of Engg. & Tech., Vijayapur",
	"B.M.S. College of Engineering",
	"Baba Banda Singh Bahadur Engineering College, Fatehgarh Sahib",
	"Baba Ghulam Shah Badshah University",
	"BABA Institute of Technology & Science, P.M. Palem, Bakkannapalem Village, Madhurawada, PIN-530048 (CC-NR)",
	"Baderia Global Institute of Engineering & Management, Jabalpur",
	"Bajaj Institute of Technology",
	"Balaji Institute of Technology & Science",
	"Ballari Institute of Technology & Management",
	"Banasthali Vidyapith",
	"Bangalore Institute of Technology, Bangalore",
	"Bankura Unnayani Institute of Engineering",
	"BANSAL INSTITUTE OF ENGINEERING & TECHNOLOGY,LUCKNOW",
	"Bansal Institute of Science & Technology, Raisen Road, Kokta, Anand Nagar, Bhopal - 462021",
	"Bansilal Ramnath Agarwal Charitable Trust`s Vishwakarama Institute of Technology",
	"Bapatla Engineering College",
	"Bapatla Women`s Engineering College",
	"BAPUJI INSTITUTE OF ENGINEERING & TECHNOLOGY",
	"Barkatullah University, Bhopal",
	"Basaveshwar Engineering College",
	"Beant College Of Engineering & Technology,Gurdaspur",
	"Bengal College of Engineering & Technology",
	"Bengal Institute of Technology",
	"BETHLAHEM INSTITUTE OF ENGINEERING",
	"Bhabha Engineering Research Institute",
	"Bhagalpur College of Engineering",
	"Bhagat Phool Singh Mahila Vishwavidyalaya (WOMEN UNIVERSITY)",
	"Bhagwan Mahavir College of Engineering and Technology",
	"Bhagwan Parshuram Institute of Technology",
	"Bharat Institute of Engineering & Technology",
	"BHARATHIYAR INSTITUTE OF ENGINEERING FOR WOMEN",
	"Bharati Vidyapeeth 'S College of Engineering for Women",
	"BHARATI VIDYAPEETH COLLEGE OF ENGINEERING, NAVI MUMBAI",
	"Bharati Vidyapeeth Deemed University College of Engineering",
	"Bharati Vidyapeeth?s College of Engineering",
	"Bharati Vidyapeeth`s College of Engineering",
	"Bharati Vidyapeeth`s College of Engineering",
	"Bharatiya Vidya Bhavan`s Sardar Patel Institute of Technology",
	"Bhilai Institute of Technology",
	"Bhimavaram Institute of Engineering & Technology, Swamy Gnananadha Ashram Road, Pennada, Bhimavaram , PIN - 534243(CC-AP)",
	"Bhubaneswar College Of Engineering",
	"Biju Patnaik University of Technology, Rourkela",
	"Bipin Tripathi Kumaon Institute of Technology",
	"Birla Institute of Technology",
	"BITS Pilani, Pilani",
	"Birla Vishvakarma Mahavidyalaya",
	"BIT Sindri",
	"BMS Institute of Technology & Management",
	"BNM INSTITUTE OF TECHNOLOGY",
	"Bonam Venkata Chalamaiah Institute of Technology and Science",
	"Bonam Venkata Chalamayya Engineering College",
	"BRAHMDEVDADA MANE INSTITUTE OF TECHNOLOGY",
	"BRAINWARE UNIVERSITY",
	"Buddha Institute of Technology",
	"Budge Budge Institute of Technology",
	"BUILDERS ENGINEERING COLLEGE",
	"Bundelkhand Institute of Engineering & Technology",
	"Bundelkhand University",
	"BVRIT Hyderabad College of Engineering for Women",
	"C K College of Engineering & Technology (Formerly Sri Jayaram Engineering College)",
	"C M R Institute of Technology",
	"C. Abdul Hakeem College of Engineering & Technology",
	"C.K.PITHAWALA COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"C.V. Raman Global University, Odisha",
	"Calcutta Institute of Engineering and Management",
	"Cambridge Institute of Technology",
	"Cambridge Institute of Technology",
	"Canara Engineering College",
	"Cape Institute of Technology",
	"CARE College of Engineering",
	"Central Institute of Plastic Engineering and Technology (CIPET), Bhubaneswar",
	"Central Institute of Plastics Engineering and Technology",
	"Central Institute of Technology",
	"Central University of Haryana",
	"Central University of Jammu",
	"Central University of Rajasthan",
	"Centurion University of Technology and Management",
	"Ch. Devi Lal State Institute of Engineering",
	"Ch. Ranbir Singh State Institute of Engineering and Technology",
	"Chadalawada Ramanamma Engineering College",
	"Chaitanya (Deemed to be University)",
	"Chaitanya Bharathi Institute of Technology",
	"CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY",
	"Chalapathi Institute of Engineering and Technology",
	"Chalapathi Institute of Technology",
	"Chandigarh College of Engineering & Technology",
	"Chandigarh Engineering College Jhanjeri",
	"Chandigarh Engineering College-CGC, Landran, Mohali",
	"Chandigarh University",
	"Chandubhai S. Patel Institute of Technology",
	"Chatrapati Sahuji Maharaj Kanpur University",
	"Chaudhary Charan Singh University Meerut",
	"CHEBROLU ENGINEERING COLLEGE",
	"Chendhuran College of Engineering & Technology",
	"Chennai Institute of Technology",
	"Chettinad College of Engineering & Technology",
	"Chhatrapati Shivaji Institute of Technology Kolihapuri",
	"Chhotubhai Gopalbhai Patel Institute of Technology",
	"Chitkara University",
	"Chitkara University",
	"Chouksey Engineering College",
	"CHRIST COLLEGE OF ENGINEERING",
	"Christ The King Engineering College",
	"Christ University",
	"Christian College of Engineering and Technology, Oddanchatram, Palani",
	"City Engineering College, BANGALORE",
	"CMR College of Engineering & Technology",
	"CMR Engineering College",
	"CMR Institute of Technology",
	"CMR Technical Campus",
	"COEP Technological University",
	"Coimbatore Institute of Engineering and Technology",
	"Coimbatore Institute of Technology",
	"College of Agricultural Engineering & Technology",
	"College of Engineering",
	"College of Engineering ,Karunagappally",
	"College of Engineering (CEB), Bhubaneswar",
	"College of Engineering & Technology",
	"College of Engineering & Technology, Bhubaneswar",
	"College of Engineering Perumon",
	"College of Engineering, Cherthala",
	"COLLEGE OF ENGINEERING, PATHANAPURAM",
	"College of Engineering, Trivandrum",
	"COLLEGE OF ENGINEERING, VADAKARA",
	"College of Food and Dairy Technology",
	"College of Technology",
	"College of Technology and Engineering",
	"COORG INSTITUTE OF TECHNOLOGY",
	"CSMSS Chh. Shahu College of Engineering",
	"CT Institute of Engg. Management and Technology, Shahpur",
	"CT University",
	"CVR College of Engineering",
	"D. M. I. College of Engineering",
	"D. N. R. College of Engineering & Technology",
	"D. Y. Patil College of Engineering & Technology",
	"D. Y. Patil Education Society, D.Y. Patil Technical Campus, Faculty of Engineering",
	"D.K.T.E.SOCIETYs TEXTILE AND ENGINEERING INSTITUTE, ICHALKARANJI",
	"Dadi Institute of Engineering & Technology (DIET)",
	"DAITA MADHUSUDANA SASTRY SRI VENKATESWARA HINDU COLLEGE OF ENGINEERING",
	"Damisetty Bala Suresh Institute of Technology",
	"Darshan Institute of Engineering & Technology",
	"DATTA MEGHE COLLEGE OF ENGINEERING",
	"DAV Institute of Engineering & Technology",
	"Dayalbagh Educational Institute",
	"Dayananda Sagar Academy of Technology & Management Technical Campus",
	"Dayananda Sagar College of Engineering",
	"Dayananda Sagar University",
	"Deenbandhu Chhotu Ram University of Science & Technology",
	"Defence Institute of Advanced Technology",
	"Delhi Global Institute of Technology",
	"DELHI TECHNICAL CAMPUS",
	"Delhi Technological University",
	"Deogiri Technical Campus for Engineering and Management Studies",
	"Desh Bhagat University",
	"Devi Ahilya Vishwavidyalaya",
	"Devineni Venkata Ramana & Dr. Hima Sekhar MIC College of Technology",
	"Dhaanish Ahmed College of Engineering",
	"Dhanalakshmi College of Engineering",
	"Dhanalakshmi Srinivasan College of Engineering",
	"DHANALAKSHMI SRINIVASAN COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Dhanalakshmi Srinivasan Engineering College",
	"DHANEKULA INSTITUTE OF ENGINEERING & TECHNOLOGY",
	"Dharmsinh Desai University",
	"Dhirajlal Gandhi College of Technology",
	"Dhirubhai Ambani Institute of Information and Communication Technology",
	"DHOLE PATIL EDUCATION SOCIETY'S, DHOLE PATIL COLLEGE OF ENGINEERING.",
	"DIBRUGARH UNIVERSITY INSTITUTE OF ENGINEERING AND TECHNOLOGY",
	"DIT University",
	"DMI Engineering College",
	"DNYANSHREE INSTITUTE OF ENGINEERING AND TECHNOLOGY, SATARA",
	"DON BOSCO COLLEGE OF ENGINEERING, FATORDA, MARGAO",
	"Don Bosco Institute Of Technology - Mumbai",
	"Don Bosco Institute of Technology, BANGALORE",
	"Dr Akhilesh Das Gupta Institute of Technology & Management",
	"Dr D Y Patil Prathisthan College of Engineering Salokhe-Nagar Kolhapur",
	"Dr D. Y. Patil Pratishthans D.Y. Patil College of Engineering, Akurdi, Pune",
	"Dr. Ambedkar Institute of Technology",
	"DR. AMBEDKAR INSTITUTE OF TECHNOLOGY FOR HANDICAPPED, U.P.",
	"Dr. B R Ambedkar National Institute of Technology Jalandhar",
	"Dr. B. R. Ambedkar Institute of Technology",
	"Dr. B.C. Roy Engineering College, Durgapur",
	"Dr. Babasaheb Ambedkar Technological University",
	"Dr. D. Y. Patil Institute of Engineering, Management and Research",
	"Dr. D. Y. Patil Institute of Technology",
	"Dr. J. J. Magdum College of Engineering, JAYSINGPUR",
	"DR. K.N. MODI INSTITUTE OF ENGINEERING AND TECHNOLOGY, MODINAGAR, GHAZIABAD",
	"Dr. Lankapalli Bullayya College of Engineering",
	"Dr. M. G. R. Educational and Research Institute",
	"Dr. Mahalingam College of Engineering and Technology",
	"Dr. N. G. P. Institute of Technology",
	"Dr. S. & S. S. Ghandhy Government Engineering College, Surat",
	"Dr. Samuel George Institute of Engineering & Technology",
	"Dr. Sivanthi Aditanar College of Engineering",
	"Dr. T. Thimmaiah Institute of Technology",
	"DR. V. R. GODHANIA COLLEGE OF ENGINEERING & TECHNOLOGY",
	"Dr. Vishwanath Karad MIT World Peace University",
	"Dr. VRK Women's College of Engineering & Technology",
	"Dr.G.U.Pope College of Engineering",
	"Dr.K.V.Subba Reddy Institute of Technology, Kurnool",
	"Dr.Rajendra Gode Institute of Technology and Research Amravati",
	"DR.SUDHIR CHANDRA SUR INSTITUTE OF TECHNOLOGY AND SPORTS COMPLEX",
	"Dream Institute of Technology",
	"Driems",
	"Dronacharya College of Engineering",
	"Dronacharya Group of Institutions",
	"Dumka Engineering College(ESTD. By Govt. of Jharkhand & Run by Techno India under PPP)",
	"Durgapur Institute of Advanced Technology and Management 155",
	"E.G.S. Pillay Engineering College",
	"East Point College of Engg., & Tech., BANGALORE",
	"East West Institute of Technology",
	"Easwari Engineering College",
	"Engineering College Bikaner",
	"Er. Perumal Manimekalai College of Engineering",
	"ERANAD KNOWLEDGE CITY TECHNICAL CAMPUS, CHERUKULAM, MANJERI",
	"Erode Sengunthar Engineering College",
	"ESHAN COLLEGE OF ENGINEERING, AGRA-MATHURA HIGHWAY, MATHURA",
	"Eswar College of Engineering",
	"Everest Education Society Sanchalit, College of Engineering",
	"EXCEL ENGINEERING COLLEGE",
	"Excelsior Education Societys K C College of Engineering Mith Bunder Road Kopri Thane (E) 400 603",
	"Fatima Michael College of Engineering and Technology, Madurai",
	"Federal Institute of Science and Technology (FISAT)",
	"Finolex Academy of Management and Technology",
	"Fr. C. Rodrigues Institute of Technology",
	"Fr. Conceicao Rodrigues College of Engineering",
	"FRANCIS XAVIER ENGINEERING COLLEGE",
	"Future Institute of Engineering and Management",
	"G H PATEL COLLEGE OF ENGINEERING & TECHNOLOGY",
	"G M Institute of Technology, DAVANGERE",
	"G S S S Institute of Engineering & Technology for Women, MYSORE",
	"G. D. Goenka University",
	"G. H. Raisoni College of Engineering, Nagpur",
	"G. I. D. C. Degree Enginering College",
	"G. K. M. College of Engineering and Technology",
	"G. L. A. University",
	"G. Madegowda Institute of Technology",
	"G. N. A. University",
	"G. Narayanamma Institute of Technology & Science for Women",
	"G. Pullaiah College of Engineering and Technology",
	"G.L.Bajaj Institute of Technology and Management",
	"G.Pulla Reddy Engineering College",
	"Galgotias College of Engineering & Technology",
	"Galgotias University",
	"Ganadipathy Tulsi's Engineering College",
	"Gandhi Engieering College (GEC)",
	"Gandhi Institute for Education and Technology (GIET), Bhubaneswar",
	"Gandhi Institute for Technological Advancement (GITA), Bhubaneswar",
	"Gandhi Institute for Technology (GIFT)",
	"GANDHI INSTITUTE OF EXCELLENT TECHNOCRATS",
	"Gandhi Institute of Technology and Management",
	"Gandhi Institute of Technology And Management (GITAM), Bhubaneswar",
	"GANESH COLLEGE OF ENGINEERING, SALEM",
	"Ganga Institute of Technology & Management",
	"Ganpat University",
	"Gargi Memorial Institute of Technology Campus",
	"Gates Institute of Technology",
	"Gateway Institute Of Engineering & Technology",
	"Gautam Buddha University",
	"Gaya College of Engineering",
	"Gayatri Vidya Parishad College for Degree and P.G Courses (Autonomous)",
	"Gayatri Vidya Parishad College of Engineering",
	"Gayatri Vidya Parishad College of Engineering for Women",
	"GCRG Memorial Trust?s Group of Institutions, Faculty of Engineering",
	"Geetanjali Institute of Technical Studies",
	"GEETHANJALI COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"GEETHANJALI INSTITUTE OF SCIENCE AND TECHNOLOGY",
	"GF's Godavari College of Engineering",
	"GHANI KHAN CHOUDHURY INSTITUTE OF ENGINEERING & TECHNOLOGY, KOTWALI, MALDA",
	"Gharda Foundations Gharda Institute of Technology",
	"GIANI ZAIL SINGH CAMPUS COLLEGE OF ENGINEERING & TECHNOLOGY BATHINDA",
	"GIET University, Gunupur",
	"Global Academy of Technology",
	"Global Institute of Engineering & Technology",
	"Global Institute of Engineering and Technology",
	"Global Institute of Technology",
	"GMR Institute of Technology",
	"Gnanamani College of Technology",
	"Goa College of Engineering (Government of Goa)",
	"Godavari Institute of Engineering & Technology",
	"Gogte Institute of Technology, BELGAUM",
	"Gojan School of Business and Technology",
	"Goka Raju Ranga Raju Institute of Engineering & Technology",
	"Gokhale Education Society's R. H. Sapat College of Engineering, Management Studies and Research",
	"Gokula Krishna College of Engineering",
	"GOUTHAMI INSTITUTE OF TECHNOLOGY & MANAGEMENT FOR WOMEN",
	"Government College of Engineering",
	"Government College of Engineering",
	"Government College of Engineering",
	"GOVERNMENT COLLEGE OF ENGINEERING",
	"Government College of Engineering",
	"Government College of Engineering",
	"Government College of Engineering",
	"Government College of Engineering",
	"Government College of Engineering (Academic Autonomous)",
	"Government College of Engineering & Ceramic Technology",
	"Government College of Engineering & Technology",
	"Government College of Engineering and Research",
	"Government College of Engineering Dharmapuri",
	"Government College of Engineering Kannur",
	"GOVERNMENT COLLEGE OF ENGINEERING THANJAVUR",
	"Government College of Engineering, Amravati",
	"Government College of Engineering, Jalgaon",
	"Government College of Technology",
	"Government Engineering College",
	"Government Engineering College",
	"Government Engineering College",
	"Government Engineering College",
	"Government Engineering College",
	"Government Engineering College",
	"Government Engineering College",
	"GOVERNMENT ENGINEERING COLLEGE BHUJ",
	"Government Engineering College Bilaspur",
	"Government Engineering College Raipur",
	"GOVERNMENT ENGINEERING COLLEGE SREEKRISHNAPURAM",
	"GOVERNMENT ENGINEERING COLLEGE, AT.KATPUR, PATAN",
	"GOVERNMENT ENGINEERING COLLEGE, BHAVNAGAR 021",
	"Government Engineering College, Jagdalpur",
	"Government Engineering College, Jhalawar",
	"GOVERNMENT ENGINEERING COLLEGE, MODASA",
	"Government Engineering College, Thrissur",
	"GOVERNMENT ENGINEERING COLLEGE, VALSAD 019",
	"Govind Ballabh Pant Institute of Engineering & Technology",
	"GOVINDRAO WANJARI COLLEGE OF ENGINEERING & TECHNOLOGY",
	"Govt Engineering College, Ballarpur road",
	"Govt. Engineering College",
	"GOVT. ENGINEERING COLLEGE KOTLA (JEORI)",
	"GOVT. ENGINEERING COLLEGE, HASSAN",
	"GOVT. ENGINEERING COLLEGE, KOZHIKODE",
	"Govt. Engineering College, Painavu P.O., ldukki- 685 603",
	"Govt. Engineering College, RAMANAGARA",
	"Govt. Mahila Engineering College,Ajmer",
	"Grace College of Engineering",
	"Graphic Era University",
	"Greater Kolkata College of Engineering and Management 236",
	"Greater Noida Institute of Technology (Engineering Institute)",
	"Group of Institutions College of Engineering, A-p. Kashti, Tal. Shrigonda,Dist.Ahmednagar",
	"GRT Institute of Engineering and Technology",
	"Gudlavalleru Engineering College",
	"GUJARAT POWER ENGINEERING & RESEARCH INSTITUTE (104)",
	"Gujarat Technological University",
	"Gulzar Group of Institutions",
	"Guru Ghasidas Vishwavidyalaya",
	"Guru Gobind Singh Educational Society's Technical Campus",
	"Guru Gobind Singh Indraprastha University",
	"Guru Jambheshwar University of Science and Technology",
	"Guru Kashi University",
	"Guru Nanak Dev Engineering College",
	"Guru Nanak Dev Engineering College, BIDAR",
	"GURU NANAK INSTITUTE OF TECHNOLOGY",
	"GURU NANAK INSTITUTE OF TECHNOLOGY",
	"Guru Nanak Institutions Technical Campus",
	"Guru Teg Bahadur Institute of Technology",
	"Gurukul Kangri Vishwavidyalaya",
	"Gurunanak Institute Of Technology",
	"Gurunank Institute of Engineering and Technology, Dahegaon",
	"GYAN GANGA COLLEGE OF TECHNOLOGY, JABALPUR",
	"Gyan Ganga Institute of Technology & Sciences",
	"H. V. P. Mandal`s College of Engineering & Technology",
	"Haji Jamaluddin Thim TrustTheem College of Engineering At Village Betegaon Boisar Chikhar Road (N.H.No.8) Near Union Park Boisar(E) Tal Palghar Dist. Thane 401 501",
	"Haldia Institute of Technology",
	"Harcourt Butler Technical University",
	"HERITAGE INSTITUTE OF TECHNOLOGY",
	"Hi-Tech Institute of Technology",
	"Himachal Pradesh University",
	"Himalayan Institute of Engineering & Technology, Sadhoura Road, Kala Amb. Distt Sirmour",
	"Hindustan College of Science & Technology",
	"Hindustan Institute of Technology and Science (HITS)",
	"Hindusthan College of Engineering and Technology",
	"Hindusthan Institute of Technology",
	"Hirasugar Instiute of Technology",
	"HKBK College of Engineering",
	"HKE`s SLN College of Engineering",
	"HMR Institute of Technology & Management",
	"Holy Mary Institute of Technology & Science",
	"Holycross Engineering College",
	"Hooghly Engineering and Technology College",
	"Hyderabad Institute of Technology & Management",
	"I. F. E. T. College of Engineering",
	"I.I.R.W's, International Centre of Excellence in Engineering and Management, Pune-Aurangabad Highway, Pandharpur.",
	"I.K. Gujral Punjab Technical University",
	"I.T.S ENGINEERING COLLEGE",
	"Ideal Institute of Engineering 279",
	"Ideal Institute of Technology",
	"Idhaya Engineering College for Women",
	"IES College of Technology, Bhopal",
	"IIMT College Of Engineering",
	"Iimt Engineering College, Meerut",
	"IIMT University Meerut",
	"Imayam College of Engineering",
	"IMS Engineering College",
	"Inderprastha Engineering College",
	"INDIAN INSTITUTE OF CARPET TECHNOLOGY",
	"Indian Institute of Engineering Science and Technology, Shibpur",
	"IIIT Allahabad",
	"IIIT Design and Manufacturing, Kurnool",
	"IIIT Guwahati",
	"IIIT, Design & Manufacturing, Kancheepuram",
	"IIIT DHARWAD",
	"IIIT KALYANI",
	"IIIT NAGPUR",
	"IIIT PUNE",
	"IIIT UNA",
	"Indian Institute of Petroleum & Energy",
	"Indian Institute of Science Education and Research Bhopal",
	"Indian Institute of Space Science and Technology",
	"IIT (Banaras Hindu University) Varanasi",
	"IIT (Indian School of Mines) Dhanbad",
	"IIT Bhilai",
	"IIT Bhubaneswar",
	"IIT Bombay",
	"IIT Delhi",
	"IIT Dharwad",
	"IIT Gandhinagar",
	"IIT Guwahati",
	"IIT Hyderabad",
	"IIT Indore",
	"IIT Jammu",
	"IIT Jodhpur",
	"IIT Kanpur",
	"IIT Kharagpur",
	"IIT Madras",
	"IIT Mandi",
	"IIT Palakkad",
	"IIT Patna",
	"IIT Roorkee",
	"IIT Ropar",
	"IIT Tirupati",
	"Indian Naval Ship Shivaji (INS Shivaji)",
	"Indira College of Engineering and Management",
	"Indira Gandhi Delhi Technical University for Women",
	"Indira Gandhi Institute of Technology (IGIT), Sarang",
	"Indore Institute of Science and Technology",
	"Indra Ganesan College of Engineering",
	"IIIT Delhi",
	"Indus International University, Bathu, Una",
	"INDUS UNIVERSITY",
	"Infant Jesus College of Engineering",
	"Info Institute of Engineering",
	"Institute of Aeronautical Engineering",
	"Institute of Chemical Technology",
	"Institute of Engg. & Rural Technology",
	"Institute of Engg. & Tech, Bhaddal",
	"Institute of Engineering & Management",
	"Institute of Engineering & Technology",
	"Institute of Infrastructure Technology Research and Management (IITRAM)",
	"Institute of Road and Transport Technology",
	"Institute of Technology and Management",
	"Institute of Technology and Management, Gorakhpur",
	"Integral University",
	"International Institute of Information Technology (I?IT)",
	"International Institute of Information Technology Bangalore",
	"International Institute of Information Technology Bhubaneswar",
	"International Institute of Information Technology Hyderabad",
	"International School of Technology & Science (Women)",
	"Invertis University",
	"IPS ACADEMY, INSTITUTE OF ENGINEERING and SCIENCE, INDORE (MP)",
	"IPS College of Technology & Management",
	"ISL Engineering College",
	"Islamic University of Science & Technology, Pulwama",
	"ITM University",
	"ITM VOCATIONAL UNIVERSITY, VADODARA",
	"J. C. Bose University of Science and Technology, YMCA",
	"J. D. College of Engineering",
	"J. K. Lakshmipat University",
	"J. N. N. College of Engineering",
	"J. N. N. Institute of Engineering",
	"J.B. Institute of Technology",
	"J.P.College of Engineering",
	"Jadavpur University",
	"Jagran Lakecity University, Bhopal",
	"Jai Hind College of Engineering, Kuran, Tal. Junnar, Dist. Pune",
	"Jai Narain College Of Technology",
	"JAI PARKASH MUKAND LAL INNOVATIVE ENGINEERING AND TECHNOLOGY INSTITUTE",
	"Jai Shriram Engineering College",
	"Jain College of Engineering, BELGAUM",
	"JAIN INSTITUTE OF TECHNOLOGY, DAVANAGERE",
	"Jain University, Bangalore",
	"Jaipur Engineering College & Research Center,jaipur",
	"Jalpaiguri Government Engineering College",
	"Jamia Hamdard",
	"Jamia Millia Islamia",
	"Jawahar Education Society's Institute of Technology Management and Research, Address: Servey No-48,Gowardhan, Gangapur Road, Nashik, Taluka: Nashik District: Nashik",
	"JAWAHARLAL COLLEGE OF ENGINEERING & TECHNOLOGY, MANGALAM",
	"Jawaharlal Darda Institute of Engineering & Technology",
	"Jawaharlal Nehru Govt.Engineering College",
	"Jawaharlal Nehru Technological University",
	"Jawaharlal Nehru Technological University",
	"Jawaharlal Nehru Technological University",
	"Jaya College Of Engineering And Technology",
	"JAYA ENGINEERING COLLEGE",
	"Jaya Institute of Technology",
	"JAYA SAKTHI ENGINEERING COLLEGE",
	"Jayaraj Annapackiam CSI College of Engineering",
	"JAYAWANTI BABU FOUNDATION+?-?-?S METROPOLITAN INSTITUTE OF TECHNOLOGY AND MANAGEMENT, SINDHUDURG",
	"Jaypee Institute of Information Technology",
	"Jaypee University of Engineering & Technology",
	"Jaypee University of Information Technology",
	"JB Institute of Engineering & Technology",
	"JCT College of Engineering and Technology",
	"JECRC University",
	"Jeppiaar Engineering College",
	"JEPPIAAR INSTITUTE OF TECHNOLOGY",
	"Jerusalem College of Engineering",
	"Jhulelal Institute of Technology",
	"JIS College of Engineering",
	"JKK Munirajah College of Technology",
	"JKKN College of Engineering and Technology",
	"JNAFAU School of Planning and Architecture",
	"Joginpally B.R Engineering College",
	"John Cox Memorial CSI Institute of Technology, Knnammoola, Thiruvananthapuram",
	"Jorhat Engineering College P.O. Jorhat-785007",
	"JSPM's Rajarshi Shahu College of Engineering",
	"JSPMs Jayawantrao Sawant College of Engineering",
	"JSS ACADEMY OF TECHNICAL EDUCATION",
	"JSS Academy of Technical Education, Noida",
	"JSS Science and Technology University",
	"Jyothi Engineering College",
	"Jyothishmathi Institute of Technology & Science",
	"JYOTHY INSTITUTE OF TECHNOLOGY",
	"K J College of Engineering & Management Research",
	"K J Somaiya Institute of Technology",
	"K S Institute of Technology, Bangalore",
	"K. G. Reddy College of Engineering & Technology",
	"K. J. S. Educational Institute`s Trinity College of Engineering and Research",
	"K. J. Somaiya College of Engineering",
	"K. K. Wagh Institute Of Engineering Education & Research",
	"K. L. N. College of Engineering",
	"K. R. Mangalam University",
	"K. Ramakrishnan College of Engineering",
	"K. Ramakrishnan College of Technology",
	"K. S. R. College of Engineering",
	"K. S. R. M. College of Engineering",
	"K.C. College of Engineering and Information Technology",
	"K.C. Education and Socail Welfare Society Group of Research & Professional Institutes, VPO pandoga, Uparla Tehsil & Distt Una",
	"K.L.E.INSTITUTE OF TECHNOLOGY",
	"K.S. Rangasamy College of Technology",
	"K.S. SCHOOL OF ENGINEERING AND MANAGEMENT",
	"K.S.K College of Engineering and Technology (New)",
	"Kakatiya Institute of Technology & Science",
	"Kakatiya University",
	"Kalaignar Karunanidhi Institute of Technology",
	"Kalasalingam Academy of Research and Education",
	"Kalinga Institute of Industrial Technology",
	"KALLAM HARANADHAREDDY INSTITUTE OF TECHNOLOGY",
	"Kalpataru Institute of Technology, TIPTUR",
	"Kalyani Charitable Trusts Late G.N.Sapkal College of Engineering , Sapkal Knowledge Hub,Kalyani Hills, Anjaneri Vadholi, Tryambakeshwar, Dist.Nashik 422212",
	"KALYANI GOVERNMENT ENGINEERING COLLEGE",
	"Kamala Institute of Technology & Science",
	"KAMARAJ COLLEGE OF ENGINEERING & TECHNOLOGY",
	"Kanpur Institute of Technology",
	"Karamvir Dadasaheb Kannamwar Engineering College, Nandanvan",
	"Karmaveer Bhaurao Patil College of Engineering",
	"Karpaga Vinayaga College of Engineering and Technology",
	"Karpagam College of Engineering",
	"Karpagam Institute of Technology",
	"Karunya Institute of Technology and Sciences",
	"Kasegaon Education Society`s Rajarambapu Institute of Technology",
	"Kashi Institute Of Technology",
	"Kasireddy Narayan Reddy College of Engineering & Research",
	"Kathir College of Engineering",
	"Kavikulguru Institute of Technology and Science",
	"KCC INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
	"KCG College of Technology",
	"Keshav Memorial Institute of Technology",
	"KGISL INSTITUTE OF TECHNOLOGY",
	"Khalsa College of Engg. and Technology",
	"Khandesh College Education Society?s College of Engineering and Management, Jalgaon",
	"KIET Group of Institutions: KIET Group of Pharmacy",
	"Kings College of Engineering",
	"KINGS ENGINEERING COLLEGE",
	"KIPM-College of Engineering and Technology (751)",
	"KKR&KSR Institute of Technology & Sciences, VINJANAMPADU Village (CC-JR)",
	"KLE Technological University",
	"KLS Vishwanathrao Deshpande Institute of Technology, Haliyal",
	"KMBB College of Engineering and Technology",
	"KMEA Engineering College",
	"Knowledge Institute of Technology",
	"Kolhapur Institute of Technology`s College of Engineering (Autonomous)",
	"Kommuri Pratap Reddy Institute of Technology",
	"Koneru Lakshmaiah Education Foundation University (K L College of Engineering)",
	"Kongu Engineering College",
	"KONGUNADU COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Koti Vidya Charitable Trusts Alamuri Ratnamala Institute of Engineering & Technology",
	"KPR Institute of Engineering and Technology",
	"Krishna School of Emerging Technology & Applied Research",
	"Krishnaswamy College of Engineering",
	"KSR INSTITUTE FOR ENGINEERING AND TECHNOLOGY, NAMAKKAL",
	"Kumaraguru College of Technology",
	"Kunwar Satyavira College of Engineering and Management",
	"Kuppam Engineering College",
	"Kurukshetra University",
	"L.D.College of Engineering, Ahmedabad 028.",
	"L.J.Institue of Engineering and technology (SFI)-Ahmedabad 032",
	"Lakireddy Bali Reddy College of Engineering (LBRCE)",
	"Lakshmi Narain College of Technology",
	"Lakshmi Narain College of Technology & Science",
	"Lakshmi Narain College of Technology Excellence",
	"Lalit Narayan Mithila University, Darbhanga",
	"Latha Mathavan Engineering College, Madurai",
	"Laxmi Institute of Technology, Valsad",
	"Laxminarayan Innovation Technological University",
	"LBS INSTITUTE OF TECHNOLOGY FOR WOMEN",
	"Lendi Institute of Engineering & Technology",
	"LINGAYAS INSTITUTE OF MANAGEMENT AND TECHNOLOGY",
	"Lord Jagannath College of Engineering and Technology",
	"Lords Institute of Engineering & Technology",
	"LOURDES MOUNT COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Lovely Professional University",
	"Loyola Institute of Technology",
	"Loyola Institute of Technology and Science",
	"Loyola-ICAM College of Engineering and Technology",
	"Lukhdhirji Engineering College",
	"M. A. M. College of Engineering",
	"M. A. M. College of Engineering and Technology",
	"M. I. E. T. Engineering College",
	"M. S. Ramaiah Institute of Technology",
	"M.A.M. School of Engineering (New)",
	"M.G.M'S COLLEGE OF ENGINEERING ,NANDED",
	"M.J.R. College of Engineering & Technology, Pulicherla",
	"M.Kumarasamy College of Engineering",
	"M.P.Nachimuthu M.Jaganathan Engineering College",
	"M.R.K. Institute of Technology",
	"M.S. Bidwe College of Engineering, Latur",
	"M.S. Ramaiah University of Applied Sciences",
	"Madan Mohan Malaviya University of Technology",
	"Madanapalle Institute of Technology & Science",
	"Madhav Institute of Technology and Science, Gole ka Mandir, P.O. Residency, Gwalior-474005",
	"MADHU VACHASPATI INSTITUTE OF ENGINEERING AND TECHNOLOGY , KAUSHAMBI",
	"Madhuben and Bhanubhai Patel Institute of Technology",
	"Maha Bharathi Engineering College",
	"Maharaj Vijayaram Gajapathi Raj College of Engineering",
	"Maharaja Agrasen Institute of Technology",
	"Maharaja Institute of Tech., Mysore",
	"Maharaja Institute of Technology, Thandavapura",
	"MAHARAJA RANJIT SINGH STATE TECHNICAL UNIVERSITY",
	"Maharaja Sayajirao University of Baroda",
	"Maharaja Surajmal Institute of Technology",
	"Maharashtra Institute of Technology",
	"Maharishi Markandeshwar (Deemed to be University)",
	"Maharshi Dayanand University, Rohtak",
	"Maharshi Karve Stree Shikshan Samstha's Cummins College of Engineering for Women",
	"Mahath Amma Institute of Engineering and Technology",
	"Mahatma Education Society's, Pillai HOC College of Engineering and technology",
	"Mahatma Gandhi Institute of Technology",
	"MAHATMA GANDHI MISSION COLLEGE OF ENGINEERING AND TECHNOLOGY, NOIDA",
	"Mahaveer Institute of Science &Technology",
	"Mahendra College of Engineering",
	"Mahendra Engineering College",
	"Mahendra Institute of Technology",
	"Mahindra University",
	"Mailam Engineering College",
	"Malaviya National Institute of Technology",
	"Malla Reddy College of Engineering and Technology (Autonomous)",
	"Malla Reddy College of Engineering for women",
	"Malla Reddy Engineering College",
	"Malla Reddy Engineering College for Women (Autonomous)",
	"Malla Reddy Institute of Engineering and Technology",
	"Malla Reddy Institute of Technology & Science",
	"Mallabhum Institute of Technology 158",
	"Malnad College of Engineering, HASSAN",
	"Manakulavinayagar Institute of Technology",
	"Manav Rachna International Institute of Research and Studies",
	"Manav Rachna University",
	"Mangalam College of Engineering, Mangalam Hills, Ettumanoor P.O, Kottayam-686 631",
	"MANGALMAY INSTITUTE OF ENGINEERING AND TECHNOLOGY, GREATER NOIDA",
	"Mangalore Institute of Technology & Engineering",
	"MANGAYARKARASI COLLEGE OF ENGINEERING",
	"Manipal Institute of Technology",
	"Manipal University, Jaipur",
	"Manipur Technical University",
	"Mar Athanasius College of Engineering, Kothamangalam, Ernakulam -686 666",
	"Mar Baselios Christian College of Engineering & Technology",
	"Mar Baselios College of Engineering and Technology",
	"Mar Baselios Institute of Technology and Science",
	"Maratha Mandal Engineering College, BELGAUM",
	"MARATHA VIDYA PRASARAK SAMAJ'S KARMAVEER ADV. BABURAO GANPATRAO THAKARE COLLEGE OF ENGINEERING",
	"Marathwada Mitra Mandal College of Engineering Pune",
	"MARATHWADA MITRA MANDAL'S INSTITUTE OF TECHNOLOGY",
	"Marian Engineering College",
	"MARRI LAXMAN REDDY INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
	"Marwadi University",
	"Matoshri Education Society's Matoshri College of Engineering & Research Centre, At-Po.Eklahare, Tal. & District- Nashik 422105.",
	"Matrusri Enginering College",
	"MATSYODARI SHIKSHAN SANSTHA'S COLLEGE OF ENGINEERING AND TECHNOLOGY, JALNA",
	"Maulana Abul Kalam Azad University of Technology",
	"Maulana Azad National Institute of Technology",
	"Maulana Azad National Urdu University",
	"MAULI GROUP OF INSTITUTIONS, COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"MBM University, Jodhpur",
	"MCKV Institute of Engineering",
	"Medi-Caps University",
	"Meenaakshi Ramaswamy Engineering College",
	"Meenakshi Sundararajan Engineering College",
	"Meerut Institute of Engineering & Technology",
	"Meerut Institute Of Technology, Baral, Partapur, Meerut",
	"Meghnad Saha Institute of Technology",
	"Mepco Schlenk Engineering College",
	"MES Engineering College",
	"Methodist College of Engineering & Technology",
	"MGM COLLEGE OF ENGINEERING AND PHARMACEUTICAL SCIENCES",
	"MGM COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"MIT Academy of Engineering",
	"MIT Art, Design and Technology University, Pune",
	"MKSSS`s Cummins College of Engineering for Women",
	"MLR Institute of Technology",
	"MNR College of Engineering & Technology",
	"Model Engineering College",
	"Model Institute of Engineering and Technology",
	"Modern Education Society`s College of Engineering",
	"Mohamed Sathak A.J. College of Engineering",
	"Mohamed Sathak Engineering College, Kilakarai",
	"MORADABAD INSTITUTE OF TECHNOLOGY",
	"Mother Terasa College of Engineering and Technology",
	"Mother Theresa Institute of Engineering and Technology",
	"Motihari College of Engineering",
	"Motilal Nehru National Institute of Technology",
	"Mount Zion College of Engineering and Technology",
	"Mount Zion College of Engineering and Technology for Women, Kozhyvalloor, Chengannur",
	"MUFFAKHAM JAH COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Muthayammal College of Engineering",
	"Muthayammal Engineering College",
	"MUTHOOT INSTITUTE OF TECHNOLOGY AND SCIENCE",
	"Muzaffarpur Institute of Technology",
	"MVJ College of Engineering",
	"MVSR Engineering College",
	"N. B. K. R. Institute of Science & Technology",
	"N. B. Navale Sinhgad College of Engineering",
	"N.P.R. College of Engineering and Technology, Natham Village, Dindigul",
	"N.S.N COLLEGE OF ENGINEERING AND TECHNOLOGY, KARUR",
	"NADAR SARASWATHI COLLEGE OF ENGINEERING & TECHNOLOGY",
	"Nadimpalli Satyanarayana Raju Institute of Technology",
	"Nagarjuna College of Engg. & Technology, BANGALORE",
	"Nagarjuna Institute of Engineering Technology and Management, Satanwari",
	"Nagesh Karajagi Orchid College of Engineering and Technology, Solapur.",
	"Nagpur Institute of Technology, Katol road",
	"NALANDA INSTITUTE OF TECHNOLOGY CHANDAKA BHUBANESWAR",
	"Nalla Malla Reddy Engineering College",
	"Nalla Narasimha Reddy Education Society`s Group of Institutions",
	"Nanasaheb Mahadik College of Engineering, Peth",
	"Nandha College of Technology",
	"Nandha Engineering College",
	"Narasaraopeta Engineering College",
	"Narayana Engineering College",
	"Narayana Engineering College",
	"Narsimhareddy Engineering College",
	"Narula Institute of Technology",
	"National Engineering College",
	"National Fire Service College",
	"National Institute of Advanced Manufacturing Technology, Ranchi",
	"National Institute of Food Technology, Enterprenurship and Management",
	"National Institute of Food Technology, Entrepreneurship and Management",
	"National Institute of Science & Technology",
	"NIT Agartala",
	"NIT Arunachal Pradesh",
	"NIT Calicut",
	"NIT Delhi",
	"NIT Durgapur",
	"NIT Goa",
	"NIT Hamirpur",
	"NIT Karnataka, Surathkal",
	"NIT Kurukshetra",
	"NIT Manipur",
	"NIT Meghalaya",
	"NIT Mizoram",
	"NIT Nagaland",
	"NIT Patna",
	"NIT Puducherry",
	"NIT Raipur",
	"NIT Rourkela",
	"NIT Sikkim",
	"NIT Silchar",
	"NIT Srinagar",
	"NIT Tiruchirappalli",
	"NIT Uttarakhand",
	"NIT Warangal",
	"NIT ANDHRA PRADESH",
	"NIT Jamshedpur",
	"Navodaya Institute of Technology, RAICHUR",
	"Navrachana University",
	"Nehru College of Engineering and Research Centre",
	"NEHRU INSTITUTE OF ENGINEERING AND TECHNOLOGY",
	"Nehru Institute of Technology",
	"Netaji Subhas University of Technology (NSUT)",
	"Netaji Subhash Engineering College",
	"New Horizon College of Engineering",
	"New Prince Shri Bhavani College of Engineering and Technology",
	"NGF College of Engineering & Technology",
	"NIIT UNIVERSITY",
	"Nimra College of Engineering & Technology",
	"Nirma University",
	"NITRA TECHNICAL CAMPUS",
	"Nitte Meenakshi Institute of Technology",
	"NMAM Institute of Technology",
	"Noida Institute of Engineering & Technology",
	"Noorul Islam Centre for Higher Education -Kanyakumari",
	"North Eastern Regional Institute of Science & Technology",
	"NRI Institute of Information Science and Technology",
	"NRI Institute of Technology",
	"NRI-INSTITUTE OF RESEARCH & TECHNOLOGY",
	"NSHM Knowledge Campus Durgapur Group of Institutions 273",
	"NSS College of Engineering",
	"OAS Institute of Technology and Management Group of Institutions (New)",
	"Omdayal Group of Institutions",
	"OP Jindal University",
	"Oriental College of Technology",
	"Oriental Institute of Science and Technology",
	"Oriental University, Indore",
	"P A College of Engineering, MANGALORE",
	"P D A College of Engineering, GULBARGA",
	"P E S College of Engineering, Mandya",
	"P. A. College of Engineering and Technology",
	"P. R. Engineering College",
	"P. R. Pote (Patil) Education & Welfare Trust's Group of Institutions's College of Engineering & Management, Amravati.",
	"P. S. R. Engineering College",
	"P.E.S. COLLEGE OF ENGINEERING",
	"P.P. Savani University",
	"P.S.R.R College of Engineering",
	"P.S.V.College of Engineering and Technology",
	"Paavai Engineering College",
	"PACE INSTITUTE OF TECHNOLOGY AND SCIENCES",
	"Padmashree Dr. D. Y. Patil Vidyapeeth, Mumbai",
	"Padmashri Dr.V.B.Kolte College of Engineering, Malkapur",
	"Padmasri Dr. B.V. Raju Institute of Technology",
	"Padre Conceicao College of Engineering",
	"Pallavi Engineering College",
	"Pandit Deendayal Energy University",
	"Pandit Dwarka Prasad Mishra IIIT, Design and Manufacturing (IIITDM) Jabalpur",
	"Panimalar Engineering College",
	"Panipat Institute of Engineering & Technology",
	"Panjab University",
	"Parala Maharaja Engineering College",
	"Parisutham Institute of Technology and Science",
	"PARK COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Parvathareddy Babulreddy Visvodaya Institute of Technology and Science",
	"Peri Institute of Technology",
	"Periyar Maniammai Institute of Science & Technology",
	"Perunthalaivar Kamarajar Institute of Engineering and Technology",
	"PES University",
	"PGP college of Engineering and Technology",
	"Phaltan Education Societys College of Engineering",
	"Pillai College of Engineering",
	"Pimpri Chinchwad College of Engineering",
	"Pimpri Chinchwad Education Trust's Pimpri Chinchwad College of Engineering and Research, Laxminagar, Ravet",
	"Pondicherry Engineering College",
	"Ponjesly College of Engineering",
	"Ponnaiyah Ramajayam Institute of Science & Technology",
	"Poornima Institute of Engineering & Technology,Jaipur",
	"Poornima University",
	"Potti Sriramulu College of Engineering & Technology, D.No.7-3-6/1, Raghava Reddy Street, Kotha Peta, Vijayawada, PIN- 520 001.(CC-KT)",
	"PPG Institute of Technology",
	"PRAGATI ENGINEERING COLLEGE",
	"PRANVEER SINGH INSTITUTE OF TECHNOLOGY, KANPUR",
	"Prasad V Potluri Siddhartha Institue of Technology",
	"Prathyusha Engineering College",
	"PRAVARA RURAL ENGINEERING COLLEGE",
	"PRESIDENCY UNIVERSITY , BENGALURU",
	"Prestige Institute Of Engineering Management & Research",
	"Prince Shri Venkateshwara Padmavathy Engineering College",
	"Priyadarshini Bhagwati College of Engineering",
	"Priyadarshini Engineering College",
	"PROF RAM MEGHE COLLEGE OF ENGINEERING & MANAGEMENT",
	"Prof. Ram Meghe Institute of Technology & Research",
	"Progressive Educational Society`s Modern College of Engineering",
	"Proudadevaraya Institute of Technology, HOSPET",
	"PROVIDENCE COLLEGE OF ENGINEERING",
	"PSG College of Technology",
	"PSG Institute of Technology and Applied Research",
	"PSGVPM'S D.N.PATEL COLLEGE OF ENGINEERING, SHAHADA, DIST-NANDURBAR.",
	"PSN COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"PSN Engineering College",
	"PSN Institute of Technology & Science",
	"PSNA College of Engineering and Technology, Dindigul",
	"Punjab Engineering College (Deemed to be University), Chandigarh",
	"Punjabi University",
	"PVG's College of Engineering and Technology and G. K. Pate (Wani) Institute of Management",
	"QIS College of Engineering & Technology",
	"Quantum University",
	"R L Jalappa Institute of Technology, DODDABALLAPURA",
	"R P Sarathy Institute of Technology",
	"R. K. College of Engineering",
	"R. M. K. College of Engineering and Technology",
	"R. N. S. Institute of Technology",
	"R. R. Institute of Modern Technology",
	"R.D.Engineering College",
	"R.M.D Engineering College",
	"R.M.K. Engineering College",
	"R.V. College of Engineering",
	"R.V. R. & J. C. College of Engineering",
	"R.V.S Engineering College, Jamshedpur",
	"R.V.S.College of Engineering",
	"Raajdhani Engineering College (REC), Bhubaneswar",
	"Rabindranath Tagore University",
	"Radhakrishna Institute of Engineering and Technology (RITE), Khurda, Bhubaneswar",
	"Raghu Engineering College",
	"Raipur Institute of Technology Chhatona, Mandir Hasaud, Raipur",
	"Raj Kumar Goel Institue of Technology",
	"RAJ KUMAR GOEL INSTITUTE OF TECHNOLOGY FOR WOMEN, GHAZIABAD",
	"Raja Balwant Singh Engineering Technical Campus",
	"Raja College of Engineering, Madurai",
	"Rajadhani Institute of Engineering and Technology",
	"Rajagiri School of Engineering and Technology (AUTONOMOUS)",
	"Rajalakshmi Engineering College",
	"Rajalakshmi Institute of Technology",
	"RAJARAJESWARI COLLEGE OF ENGINEERING",
	"Rajasthan Technical University, Kota",
	"Rajeev Gandhi Memorial College of Engineering & Technology",
	"Rajeev Institute of Technology, HASSAN",
	"Rajendra Mane College of Engineering & Technology",
	"Rajiv Gandhi College of Engineering and Technology",
	"Rajiv Gandhi College of Engineering, Research and Technology",
	"Rajiv Gandhi Govt. Engineering College",
	"Rajiv Gandhi Institute of Petroleum Technology",
	"Rajiv Gandhi Institute of Technology",
	"Rajiv Gandhi Proudyogiki Vishwavidyalaya",
	"Rajiv Gandhi University of Knowledge Technologies",
	"Rajkiya Engineering College Banda",
	"Rajkiya Engineering College, Ambedkar Nagar",
	"Rajkiya Engineering College, Azamgarh",
	"Rajkiya Engineering College, Kannauj",
	"Rajkiya engineering college, sonbhadra",
	"Rajshree Institute of Management & Technology",
	"RAMA UNIVERSITY UTTAR PRADESH",
	"Ramachandra College of Engineering",
	"Ramco Institute of Technology",
	"Rami Reddy Subbarami Reddy Engineering College",
	"Ranganathan Engineering College",
	"Rao Bahaddur Y Mahabaleshwarappa Engineering College",
	"Rathinam Technical Campus",
	"Ravindra College of Engineering for Women",
	"RAYAT BAHRA UNIVERSITY",
	"RCC Institute of Information Technology",
	"Regent Education & Research Foundation Group of Institutions",
	"Reva University",
	"Rewa Engineering College",
	"RIMT University",
	"RISE Krishna Sai Prakasam Group of Institutions",
	"RKDF University",
	"Roever Engineering College",
	"Rohini College of Engineering And Technology",
	"Roorkee Institute of Technology",
	"RRASE College of Engineering",
	"Rungta College of Engineering & Technology",
	"Rustamji Institute of Technology",
	"RVS College of Engineering and Technology",
	"RVS Educational Trust`s Group of Institutions",
	"S G Balekundri Institute of Technology, BELGAUM",
	"S J C INSTITUTE OF TECHNOLOGY",
	"S. A. Engineering College",
	"S. B. Jain Institute of Technology Management and Research",
	"S. B. Patil College of Engineering",
	"S. D. M. College of Engineering & Technology",
	"S.D. Bansal College of Engg., Indore",
	"S.D. Bansal College of Technology, Umariya, A.B.Road, Indore",
	"S.R.M. Institute of Science and Technology",
	"S.V.P.M. College of Engineering, Malegaon bk., Tal. Baramati, Dist Pune 413115",
	"S.Veerasamy Chettiar College of Engineering",
	"SACRED HEART INSTITUTE OF MANAGAMENT AND TECHNOLOGY, SITAPUR",
	"SACS MAVMM Engineering College, Madurai",
	"Sagar Institute of Research & Technology",
	"Sagar Institute of Research & Technology Excellence",
	"Sagar Institute of Science & Technology, Gandhi Nagar, Pipalner Near Airport, Jaipur Road, NH 12, Bhopal - 462036",
	"Sagar Institute of Science Technology & Research (SISTEC-R)",
	"Sagar Institute of Science Technology and Engineering (SISTec-E), Sikandrabad, Near Ratibad, Bhadbhada Road, Bhopal",
	"SAGE University Indore",
	"Sagi Ramakrishnam Raju Engineering College",
	"Sahrdaya College of Engineering & Technology",
	"Sahyadri College of Engineering & Management",
	"Sai Vidya Institute of Technology",
	"Saintgits College of Engineering",
	"SAL INSTITUTE OF TECHNOLOGY & ENGINEERING RESEARCH",
	"Salem College of Engineering and Technology",
	"SAMARTH RURAL EDUCATIONAL INSTITUTE, RAJURIs SAMARTH GROUP OF INSTITUTIONS FACULTY OF ENGINEERING, JUNNAR",
	"Samskruti College of Engineering & Technology",
	"Sandip Foundation's Sandip Institute of Engineering and Management",
	"Sangam University",
	"SANJAY GHODAWAT UNIVERSITY",
	"SANJEEVAN ENGINEERING & TECHNOLOGY INSTITUTE",
	"SANJIVANI RURAL EDUCATION SOCIETY'S COLLEGE OF ENGINEERING",
	"Sanketika Vidya Parishad Engineering College",
	"Sanmati Engineering College",
	"Sanskar College of Engineering & Technology",
	"Sanskrithi School of Engineering",
	"Sanskriti University",
	"SANT GAJANAN MAHARAJ COLLEGE OF ENGINEERING, KOLHAPUR",
	"Sant Longowal Institute of Engineering and Technology",
	"Santhiram Engineering College",
	"Saranathan College of Engineering",
	"Saraswati Education Society`s Saraswati College of Engineering",
	"SARASWATI HIGHER EDUCATION AND TECHNICAL COLLEGE OF ENGINEERING, VARANASI",
	"Sardar Patel College of Engineering",
	"SARDAR PATEL COLLEGE OF ENGINEERING",
	"Sardar Vallabhbhai National Institute of Technology",
	"Sarvajanik College of Engineering & Technology",
	"Sasi Institute of Technology & Engineering",
	"Sasurie College of Engineering",
	"Sathyabama Institute of Science and Technology",
	"Saveetha Engineering College",
	"Saveetha Institute of Medical and Technical Sciences",
	"SCAD College of Engineering and Technology",
	"Scholar's Institute Of Technology & Management",
	"School of Engineering and Technology",
	"SCHOOL OF MANAGEMENT SCIENCES, LUCKNOW",
	"Scient Institute of Technology",
	"SCMS School of Engineering & Technology",
	"SCTR's Pune Institute of Computer Technology",
	"SDM INSTITUTE OF TECHNOLOGY UJIRE-574240",
	"SEA College of Engineering & Technology, BANGALORE",
	"Selvam College of Technology",
	"Sengunthar Engineering College",
	"SES'S R.C.PATEL INSTITUTE OF TECHNOLOGY, SHIRPUR",
	"Seth Jai Parkash Mukand Lal Inst. of Engineering & Technology",
	"Sethu Institute of Technology",
	"SF's Sandip Institute of Technology and Research Centre",
	"Shadan College of Engineering & Technology",
	"Shadan Women's College of Engineering & Technology",
	"Shah And Anchor Kutchhi Engineering College",
	"Shaheed Bhagat Singh State University",
	"Shanmuganathan Engineering College",
	"Shanmugha Arts Science Technology and Research Academy",
	"Shantilal Shah Engineering College",
	"SHARAD INSTITUTE OF TECHNOLOGY COLLEGE OF ENGINEERING",
	"Sharda University",
	"Sharnbasva University",
	"SHETTY INSTITUTE OF TECHNOLOGY, GULBARGA",
	"Shivajirao S. Jondhale College of Engineering",
	"Shivalik College of Engg.",
	"Shoolini University of Biotechnology and Management Sciences",
	"SHREE L R TIWARI COLLEGE OF ENGINEERING, THANE",
	"Shree Ramchandra College of Enginnering",
	"Shree Swami Atmanand Saraswati Institute of Technology",
	"Shree Venkateshwara Hi-Tech Engineering College",
	"Shreeyash Pratishthan`s Shreeyash College of Engineering and Technology",
	"Shri Ambabai Talim Sanstha's Sanjay Bhokre Group of Institutes, Miraj",
	"Shri Balasaheb Mane Shikshan Prasarak Mandal Ambap`s Ashokrao Mane Group of Institutions",
	"Shri G. S. Institute of Technology & Science",
	"SHRI GURU GOBIND SINGHJI INSTITUTE OF ENGINEERING AND TECHNOLOGY",
	"Shri Labhubhai Trivedi Institute of Engineering and Technology",
	"SHRI MADHWA VADIRAJA INSTITUTE OF TECHNOLOGY AND MANAGEMENT",
	"Shri Mata Vaishno Devi University",
	"Shri Neminath Jain Brahmacharyashramas College of Engineering, Neminagar, Chandwad, Dist.Nashik 423101",
	"Shri Ram Institute of Technology, ITI, Madhotal, Jabalpur-482002",
	"Shri Ram Murti Smarak College of Engineering & Technology",
	"Shri Ram Murti Smarak College of Engineering Technology & Research, Bareilly",
	"Shri Ramdeobaba College of Engineering and Management",
	"Shri Ramswaroop Memorial College of Engineering & Management",
	"SHRI SADVIDHYA MANDAL INSTITUTE OF TECH., BHARUCH 045",
	"Shri Sant Gajanan Maharaj Engineering College, Shegaon.",
	"Shri Shankaracharya Institute of Professional Management & Technology",
	"Shri Shankaracharya Technical Campus",
	"SHRI SHIVAJI VIDYA PRASARAK SANSTHA'S LATE BAPUSAHEB SHIVAJIRAO DEORE COLLEGE OF ENGINEERING, DHULE",
	"SHRI SITARAMBHAI NARANJI PATEL INSTITUTE OF TECHNOLOGY, MANAGED BY VIDYABHARTI TRUST,UMRAKH -BARDOLI",
	"Shri Vaishnav Vidyapeeth Vishwavidyalaya",
	"Shri Vile Parle Kelavani Mandal?s Institute of Technology, Dhule",
	"Shri Vile Parle Kelavani Mandal`s Dwarkadas J. Sanghvi College of Engineering",
	"Shri Vishnu Engineering College for Women",
	"Shridevi Institute of Engg, & Technology, TUMKUR",
	"Shroff S. R. Rotary Institute of Chemical Technology",
	"Siddaganga Institute of Technology",
	"Siddartha Educational Academy Group of Institutions (Integrated Campus)",
	"SIDDARTHA INSTITUTE OF SCIENCE AND TECHNOLOGY",
	"Siddharth Institute of Engineering & Technology",
	"Siddhartha Institute of Engineering & Technology",
	"Siddhivinayak Technical Campus",
	"SIES Graduate School of Technology",
	"SIGMA UNIVERSITY",
	"Sikkim Manipal Institute of Technology (SMIT)",
	"Siksha `O` Anusandhan",
	"Silicon Institute of Technology (SIT), Bhubaneswar",
	"Sinhgad Academy of Engineering",
	"Sinhgad College of Engineering",
	"Sinhgad Technical Education Society`s Sinhgad Institute of Technology",
	"Sinhgad Technical Education Society`s Sinhgad Institute of Technology & Science",
	"SINHGAD TECHNICAL EDUCATION SOCIETYS NBN SINHGAD TECHNICAL INSTITUTES CAMPUS, PUNE",
	"SINHGAD TECHNICAL EDUCATION SOCIETYS RASIKLAL M DHARIWAL SINHGAD TECHNICAL INSTITUTES CAMPUS, PUNE",
	"Sipna College of Engineering and Technology, Amravati",
	"SIR C R REDDY COLLEGE OF ENGINEERING",
	"Sir C. V. Raman Institute of Technology & Sciences",
	"Sir Isaac Newton College of Engineering and Technology (New)",
	"Sir M Visvesvaraya Institute of Technology, BANGALORE",
	"Sitamarhi Institute of Technology",
	"Sityog Institute of Technology",
	"SJB Institute Of Technology",
	"SKN SINHAGAD COLLEG OF ENGINEERING KORTI TAL PANDHARPUR DIST-SOLAPUR",
	"SKN SINHGAD INSTITUTE OF TECHNOLOGY & SCIENCE",
	"Smt. Kamala & Vekappa M Agadi College of Engg. & Technology, Lakshmeshwara",
	"Smt. Kashibai Navale College of Engineering",
	"SNS College of Engineering",
	"SNS College of Technology",
	"Sona College of Technology",
	"Sphoorthy Engineering College",
	"SR University",
	"SREE BUDDHA COLLEGE OF ENGINEERING, PATTOOR",
	"Sree Chaitanya College of Engineering",
	"Sree Chaitanya Institute of Technological Sciences",
	"Sree Chitra Thirunal College of Engineering, Pappanamcode, Thiruvanthapuram",
	"SREE DATTHA INSTITUTE OF ENGINEERING AND SCIENCE",
	"Sree Rama Engineering College",
	"Sree Sakthi Engineering College",
	"Sree Sastha Institute of Engineering and Technology",
	"Sree Sowdambika College of Engineering",
	"Sree Venkateswara College of Engineering",
	"Sree Vidyanikethan Engineering College",
	"Sreenidi Institute of Science &Technology",
	"Sreenivasa Institute of Technology and Management Studies",
	"SREEPATHY INSTITUTE OF MANAGEMENT & TECHNOLOGY, VAVANOOR",
	"Sreyas Institute of Engineering & Technology",
	"Sri Balaji Chockalingam Engineering College",
	"Sri Bharathi Engineering College for Women",
	"Sri Channabasaveshwara Institute of Technology, GUBBI",
	"Sri Eshwar College of Engineering",
	"Sri Guru Granth Sahib World University",
	"Sri Indu College of Engineering and Technology",
	"Sri Indu Institute of Engineering and Technology",
	"SRI JAYARAM INSTITUTE OF ENGINEERING AND TECHNOLOGY",
	"Sri Krishana Institute of Technology, BANGALORE",
	"Sri Krishna College of Engineering and Technology",
	"Sri Krishna College of Technology",
	"Sri Manakula Vinayagar Engineering College",
	"Sri Mittapalli College of Engineering",
	"Sri Mittapalli Institute of Technology for Women",
	"Sri Muthukumaran Institute of Technology",
	"Sri Padmavathi Mahila Visvavidyalayam",
	"SRI RAMAKRISHNA COLLEGE OF ENGINEERING",
	"Sri Ramakrishna Engineering College",
	"Sri Ramakrishna Institute of Technology",
	"SRI RANGANATHAR INSTITUTE OF ENGINEERING AND TECHNOLOGY, COIMBATORE",
	"Sri Sai Ram Institute of Technology",
	"Sri Sairam College of Engineering",
	"Sri Sairam Engineering College",
	"Sri Sarathi Institute of Engineering & Technoology",
	"Sri Satya Sai University of Technology & Medical Sciences, Sehore",
	"Sri Shakthi Institute of Engineering and Technology",
	"Sri Shankarprasad College of Engineering, Sindi meghe",
	"SRI SHANMUGHA COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Sri Siddhartha Academy of Higher Education",
	"Sri Sivasubramaniya Nadar College of Engineering",
	"SRI VASAVI ENGINEERING COLLEGE",
	"Sri Vasavi Institute of Engineering & Technology",
	"Sri Venkatesa Perumal College of Engineering & Technology",
	"SRI VENKATESHWARA COLLEGE OF ENGINEERING",
	"Sri Venkateswara College of Engineering",
	"Sri Venkateswara College of Engineering",
	"Sri Venkateswara College of Engineering and Technology",
	"Sri Venkateswara College of Engineering, Tirupati",
	"Sri Venkateswara University",
	"Sri Venkateswaraa College of Technology",
	"Sridevi Womens Engineering College",
	"Srinath University",
	"SRINIVAS INSTITUTE OF TECHNOLOGY",
	"Srinivas University",
	"Srinivasa Ramanujan Institute of Technology",
	"Sriram Engineering College",
	"SRK Institute of Technology, Enikepadu",
	"SRM University Delhi - NCR",
	"SRM Valliammai Engineering College",
	"SSBT's College of Engineering & Technology",
	"SSM College of Engineering",
	"SSM COLLEGE OF ENGINEERING",
	"SSM Institute of Engineering and Technology",
	"ST ANNS COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"St. Francis Institute of Technology",
	"St. Joseph College of Engineering",
	"ST. JOSEPH ENGINEERING COLLEGE",
	"St. Joseph`s College of Engg. and Technology",
	"St. Joseph`s Institute of Technology",
	"St. Josephs College of Engineering",
	"St. Martin's Engineering College",
	"St. Michael College of Engineering and Technology, Kalayarkoil, Sivagangai Dist",
	"St. Mother Theresa Engineering College",
	"St. Peter's Engineering College",
	"St. Peter`s College of Engineering and Technology",
	"St. Thomas College of Engineering & Technology 122",
	"St. Vincent Palloti College of Engineering and Technology",
	"St. Xavier`s Catholic College of Engineering",
	"St.Anne's College of Engineering and Technology",
	"Stanley College of Engineering & Technology for Women",
	"Stella Mary`s College of Engineering",
	"Sudharsan Engineering College",
	"Supreme Knowledge Foundation Group of Institutions",
	"Surya Engineering College",
	"Suryodaya College of Engineering and Technology, Nagpur",
	"SVERI's College of Engineering, Pandharpur",
	"SVKM`s Narsee Monjee Institute of Management Studies",
	"SVR Engineering College, Nandyal",
	"Swami Keshvanand Institute of Technology, Management & Gramothan",
	"Swami Vivekanand College of Engineering, Khandwa Road, Near Tool Naka, Indore-452020",
	"Swami Vivekanand Institute of Engg. & Technology, Ramnagar",
	"Swami Vivekanand Subharti University",
	"SWARNANDHRA COLLEGE OF ENGINEERING & TECHNOLOGY",
	"SYED AMMAL ENGINEERING COLLEGE",
	"Synergy Institute of Engineering & Technology",
	"T John Institute Of Technology",
	"T. K. M. Institute of Technology",
	"T.J.S. Engineering College",
	"Tagore Engineering College",
	"Tagore Institute of Engineering and Technology",
	"Tamil Nadu Dr.J.Jayalalithaa Fisheries University",
	"Tamilnadu College of Engineering",
	"Tatyasaheb Kore Institute of Engineering & Technology, WARANANAGAR",
	"TECHNO INDIA AGARTALA",
	"Techno India Chaibasa",
	"Techno India Ramgarh",
	"TECHNO INTERNATIONAL BATANAGAR",
	"TECHNO INTERNATIONAL NEW TOWN",
	"Techno Main Salt Lake",
	"Technocrats Institute Of Technology",
	"Technocrats Institute of Technology (Excellence), Anand Nagar, PB No. 24, Post Piplani, BHEL, Bhopal - 462021",
	"Technology Education & Research Institute",
	"Teegala Krishna Reddy Engineering College",
	"Terna Public Charitable Trust's Terna Engineering College",
	"Terna Public Charitable Trust`s College of Engineering",
	"Tezpur University",
	"Thadomal Shahani Engineering College",
	"Thakur College of Engineering & Technology",
	"THAMIRABHARANI ENGINEERING COLLEGE, TIRUNELVELI",
	"THANTHAI PERIYAR GOVERNMENT INSTITUTE OF TECHNOLOGY",
	"Thapar Institute of Engineering and Technology (Deemed-to-be-university)",
	"The Assam Kaziranga University",
	"The Institute of Chartered Financial Analysts of India University",
	"The Kavery Engineering College",
	"The LNM Institute of Information Technology, Jaipur",
	"The National Institute of Engineering",
	"THE NEOTIA UNIVERSITY",
	"The Northcap University",
	"The Oxford College of Engineering",
	"Theni Kammavar Sangam College of Technology",
	"Thiagarajar College of Engineering",
	"Thiruvalluvar College of Engineering and Technology",
	"TKM College of Engineering",
	"TKR College of Engineering & Technology",
	"Toc-H Institute of Science and Technology, Arakunnam",
	"Tontadarya College of Engineering",
	"Transnational Knowledge Society's Group of Institutions, Indore",
	"Trichy Engineering College",
	"Trident Academy of Technology (TAT)",
	"Tripura Institute of Technology",
	"TRP Engineering College (New)",
	"Truba Institute of Engineering & Information Technology, Karod-Gandhi Nagar By-Pass Road, Bhopal-462036",
	"Tulas Institute",
	"TULSIRAMJI GAIKWAD-PATIL COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"UBDT College of Engineering, Davanagere",
	"Ujjain Engineering College",
	"UNITED INSTITUTE OF TECHNOLOGY",
	"Universal Institute of Engineering & Technology",
	"University College of Engineering",
	"University College of Engineering",
	"University College of Engineering Nagercoil",
	"University College of Engineering, BIT Campus Tiruchirappalli",
	"UNIVERSITY COLLEGE OF TECHNOLOGY (Autonomous)",
	"University Institute of Chemical Technology",
	"University of Allahabad",
	"University of Engineering and Management",
	"University of Hyderabad",
	"University of Lucknow",
	"University Visvesvaraya College of Engineering",
	"Unnamalai Institute of Technology",
	"UPES",
	"Usha Mittal Institute of Technology for Women",
	"Usha Rama College of Engineering & Technology",
	"Uttar Pradesh Textile Technology Institute",
	"V V College of Engineering",
	"V. S. B. Engineering College",
	"V.R.S. College Of Engineering and Technology",
	"V.S.B College of Engineering Technical Campus",
	"V.S.M College of Engineering",
	"Vaagdevi College of Engineering",
	"Vaagdevi Institute of Technology and Science",
	"Vageswari College of Engineering",
	"Valia Koonambaikulathamma College of Engineering and Technology",
	"Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology",
	"Vardhaman College of Engineering",
	"Vasantdada Patil Pratishthan's College of Engineering and Visual Arts",
	"Vasavi College of Engineering",
	"Vasireddy Venkatadri Institute of Technology",
	"Vedavyasa Institute of Technology",
	"Veer Bahadur Singh Purvanchal University, Jaunpur",
	"Veer Surendra Sai University of Technology",
	"Veerappa Nisty Engineering College, HASNAPUR",
	"Veermata Jijabai Technological Institute, (VJTI, Mumbai)",
	"Vel Tech High Tech Dr. Rangarajan Dr. Sakunthala Engineering College",
	"VEL TECH MULTI TECH DR.RANGARAJAN DR.SAKUNTHALA ENGINEERING COLLEGE",
	"Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology",
	"Velagapudi Ramakrishna Siddhartha Engineering College",
	"Velalar College of Engineering and Technology",
	"Velammal College of Engineering & Technology",
	"Velammal Engineering College",
	"Velammal Institute of Technology",
	"Vellore Institute of Technology",
	"Vels Institute of Science Technology and Advanced Studies (VISTAS)",
	"Vemana Institute of Technology",
	"Vemu Institute of Technology",
	"Vidya Academy of Science & Technology",
	"Vidya Jyothi Institute of Technology",
	"VIDYA PRASARAK MANDAL'S MAHARSHI PARSHURAM COLLEGE OF ENGINEERING",
	"Vidya Pratishthan's Kamalnayan Bajaj Institute of Engineering & Technology, Baramati, M.I.D.C.road, District - Pune",
	"Vidya Vihar Institute of Technology",
	"Vidya Vikas Education Trust Universal College of Engineering, Thane",
	"Vidya Vikas Institute of Engineering & Technology",
	"Vidyaa Vikas College of Engineering and Technology",
	"Vidyalankar Institute of Technology Pearl Center",
	"Vidyavardhaka College of Engineering, MYSORE",
	"VIDYAVARDHINI'S COLLEGE OF ENGINEERING AND TECHNOLOGY",
	"Vighnaharta Trust s Shivajirao S Jondhale College of Engineering &Technology Asangaon Tal Shahapur Dist Thane",
	"Vignan Institute of Technology and Science",
	"Vignan's Foundation for Science, Technology and Research",
	"VIGNAN'S INSTITUTE OF ENGINEERING FOR WOME",
	"Vignan's Institute of Management & Technology for Women",
	"Vignan`s Institute of Information Technology",
	"Vignan`s Lara Institute of Technology & Science",
	"Vignan`s Nirula Institute of Technology & Science for Women",
	"Vignana Bharathi Institute of Technology",
	"VIJAYA INSTITUTE OF TECHNOLOGY FOR WOMEN",
	"Vikas College of Engineering and Technology, Nunna, Vijayawada (Rural), PIN-521212(CC-NQ)",
	"Vikas Group of Institutions",
	"Vikrant Institute of Technology and Management, Borkhedi, Behind Veterinary College, AB Road, Indore- 453446",
	"Vimal Jyothi Engineering College",
	"Vinayaka Mission's Research Foundation",
	"Vins Christian College of Engineering",
	"Visakha Institute of Engineering & Technology",
	"VISAT ENGINEERING COLLEGE",
	"Vishnu Institute of Technology",
	"VISHWAKARMA GOVERNMENT ENGINEERING COLLEGE CHANDKHEDA",
	"Vishwakarma Institute of Information Technology",
	"Vishwakarma University, Pune",
	"VISHWANIKETANs INSTITUTE OF MANAGEMENT ENTREPRENEURSHIP and ENGINEERING TECHNOLOGY",
	"VISHWAVIDYALAYA ENGINEERING COLLEGE, AMBIKAPUR (A CONSTITUENT COLLEGE OF CSVTU, BHILAI)",
	"Visvesvaraya National Institute of Technology Nagpur",
	"Visvesvaraya Technological University",
	"Viswam Engineering College",
	"Vivekanand Education Society`s Institute of Technology Sindhi Society",
	"Vivekananda College of Engg. & Tech., PUTTUR",
	"VIVEKANANDA GLOBAL UNIVERSITY",
	"Vivekananda Institute of Technology, Bangalore",
	"Vivekanandha College of Engineering for Women",
	"Vivekanandha College of Technology for Women",
	"Walchand College of Engineering",
	"Walchand Institute of Technology",
	"Wellfare Institute of Science, Technology and Management",
	"Xavier Institute of Engineering, Mahim, Mumbai - 400016",
	"Yashoda Technical Campus, Faculty of Engineering, Wadhe",
	"Yeshwantrao Chavan College of Engineering",
];

export default colleges;
